trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
    - job: firstjob
      steps:
      - bash: ls -lrta  $(System.DefaultWorkingDirectory)
      - bash: echo $(System.DefaultWorkingDirectory)
      - bash: echo $(Time)